//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondApp.EntityModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PropMenuGastronomicThings_Dictionary_First
    {
        public int Id { get; set; }
        public string ThingName { get; set; }
        public Nullable<float> NettoMini { get; set; }
        public Nullable<byte> Vat { get; set; }
        public string MergeType { get; set; }
        public string SpecificType { get; set; }
        public string SpecificType1 { get; set; }
    }
}
