//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondApp.EntityModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PropClient
    {
        public int Id_proposition { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdress { get; set; }
        public string NIP { get; set; }
        public string CustomerFullName { get; set; }
        public string PhoneNum { get; set; }
        public string DecisingPersonFullName { get; set; }
        public string CustomerEmail { get; set; }
    
        public virtual Proposition Proposition { get; set; }
    }
}
