//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondApp.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PropPaymentSuggestions
    {
        public int Id { get; set; }
        public int Id_proposition { get; set; }
        public string PaymentForm { get; set; }
        public string InvoiceServiceName { get; set; }
        public string IndividualOrders { get; set; }
        public string CarPark { get; set; }
        public string HallDescription { get; set; }
    
        public virtual Proposition Proposition { get; set; }
    }
}
