//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondApp.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PropReservationDetails_Dictionary_HallPrices
    {
        public int Id { get; set; }
        public string Hall { get; set; }
        public Nullable<int> January { get; set; }
        public Nullable<int> Febuary { get; set; }
        public Nullable<int> March { get; set; }
        public Nullable<int> April { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> June { get; set; }
        public Nullable<int> July { get; set; }
        public Nullable<int> August { get; set; }
        public Nullable<int> September { get; set; }
        public Nullable<int> October { get; set; }
        public Nullable<int> November { get; set; }
        public Nullable<int> December { get; set; }
        public Nullable<int> Other { get; set; }
    }
}
