//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondApp.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PropReservationDetails_Dictionary_HallCapacity
    {
        public int Id { get; set; }
        public string Hall { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> TheatrePeopleNumber { get; set; }
        public Nullable<int> UShapePeopleNumber { get; set; }
    }
}
