//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondApp.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Users
    {
        public Users()
        {
            this.Proposition = new ObservableCollection<Proposition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PhoneNum { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstLogin { get; set; }
    
        public virtual AccountPrivileges AccountPrivileges { get; set; }
        public virtual ObservableCollection<Proposition> Proposition { get; set; }
    }
}
